name: Build on push
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: gh-pages # The branch the action should deploy from.
        BRANCH: master # The branch the action should deploy to.
        FOLDER: docs # The folder the action should deploy.
        BUILD_SCRIPT: npm install && npm run build
